title: Ryan M. Imrie
description: Virology, bioinformatics, and modelling.
baseurl: ""
url: "https://ryanmimrie.github.io"
twitter_username: ryanmimrie
github_username:  ryanmimrie

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
